### ISSUE TITLE
Plugin does to seem to work with Vagrant 1.9.1

### ISSUE THREAD

**Issue by MarcinOrlowski** [kusnier/vagrant-persistent-storage#66] opened 2017-04-17 16:16 UTC
Your plugin does to seem to work at all with Vagrant 1.9.1 here. Host and guest are both Debian 8.  The config is pretty c&p from docs:

    config.persistent_storage.enabled = true
    config.persistent_storage.location = "~/vdi/ftp.vdi"
    config.persistent_storage.size = 5000
    config.persistent_storage.mountname = 'ftp'
    config.persistent_storage.filesystem = 'xfs'
    config.persistent_storage.mountpoint = '/FTP'
    config.persistent_storage.use_lvm = false

Nothing happens on `vagrant up` and the `~/vdi` folder remains empty. I also tried with vbguest installed but that makes no difference.

Is it me or plugin is not working with recent Vagrant?

**Comment by realyst2k** [comment] 2017-04-24 13:28
Confirmed here on Vagrant 1.9.3. Required a reinstall of the plugin but now fails to mount properly on  a CentOS5 box.

**Comment by realyst2k** [comment] 2017-04-24 14:39
I am able to confirm with newest Vagrant and plugin version, that it fails to mount properly. It appears to load the plugin successfully, even echoing "Persistent Storage Volume exists, not creating ** " and "** Attaching persistent storage **", but the disk remains unmounted.

**Comment by realyst2k** [comment] 2017-04-24 15:35
Config:

`
    config.persistent_storage.enabled = true
    config.persistent_storage.location = projectdisk
    config.persistent_storage.size = 10000
    config.persistent_storage.mountname = 'projects'
    config.persistent_storage.filesystem = 'ext3'
    config.persistent_storage.mountpoint = '/mnt/projdisk'
    config.persistent_storage.volgroupname = 'diskgrp'
`

**Comment by realyst2k** [comment] 2017-04-24 18:03
Now I can't get my disk to mount even on a downgraded Vagrant.

**Comment by realyst2k** [comment] 2017-04-24 18:06
```
==> Virtual_Dev: ** Attaching persistent storage **
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="VirtualDevEnvironment_Virtual_Dev_1493053977383_33473"
groups="/"
ostype="Red Hat (64-bit)"
UUID="592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0"
CfgFile="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473.vbox"
SnapFldr="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/Snapshots"
LogFldr="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/Logs"
hardwareuuid="592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0"
memory=4096
pagefusion="off"
vram=12
cpuexecutioncap=75
hpet="off"
chipset="piix3"
firmware="BIOS"
cpus=4
pae="on"
longmode="on"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="floppy"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="legacy"
VMState="poweroff"
VMStateChangeTime="2017-04-24T18:00:24.383000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="IDE"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="5"
storagecontrollerbootable1="on"
"IDE-0-0"="none"
"IDE-0-1"="none"
"IDE-1-0"="emptydrive"
"IDE-IsEjected"="off"
"IDE-1-1"="none"
"SATA-0-0"="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/box-disk1.vmdk"
"SATA-ImageUUID-0-0"="ac1b19fb-9c5e-43dd-b966-5387566d1130"
"SATA-1-0"="none"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
natnet1="nat"
macaddress1="0800270B3C2B"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="tcp2223,tcp,,2223,,22"
hostonlyadapter2="vboxnet0"
macaddress2="080027C1621A"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="coreaudio"
clipboard="bidirectional"
draganddrop="hosttoguest"
vrde="off"
usb="on"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="home_Virtual_shared"
SharedFolderPathMachineMapping1="/Users/realyst/VirtualDevEnvironment/shared"
SharedFolderNameMachineMapping2="vagrant"
SharedFolderPathMachineMapping2="/Users/realyst/VirtualDevEnvironment"
vcpenabled="off"
vcpscreens=0
vcpfile="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: name="VirtualDevEnvironment_Virtual_Dev_1493053977383_33473"
groups="/"
ostype="Red Hat (64-bit)"
UUID="592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0"
CfgFile="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473.vbox"
SnapFldr="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/Snapshots"
LogFldr="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/Logs"
hardwareuuid="592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0"
memory=4096
pagefusion="off"
vram=12
cpuexecutioncap=75
hpet="off"
chipset="piix3"
firmware="BIOS"
cpus=4
pae="on"
longmode="on"
cpuid-portability-level=0
bootmenu="messageandmenu"
boot1="floppy"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="legacy"
VMState="poweroff"
VMStateChangeTime="2017-04-24T18:00:24.383000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="IDE"
storagecontrollertype0="PIIX4"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="2"
storagecontrollerportcount0="2"
storagecontrollerbootable0="on"
storagecontrollername1="SATA"
storagecontrollertype1="IntelAhci"
storagecontrollerinstance1="0"
storagecontrollermaxportcount1="30"
storagecontrollerportcount1="5"
storagecontrollerbootable1="on"
"IDE-0-0"="none"
"IDE-0-1"="none"
"IDE-1-0"="emptydrive"
"IDE-IsEjected"="off"
"IDE-1-1"="none"
"SATA-0-0"="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/box-disk1.vmdk"
"SATA-ImageUUID-0-0"="ac1b19fb-9c5e-43dd-b966-5387566d1130"
"SATA-1-0"="none"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
natnet1="nat"
macaddress1="0800270B3C2B"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="tcp2223,tcp,,2223,,22"
hostonlyadapter2="vboxnet0"
macaddress2="080027C1621A"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="coreaudio"
clipboard="bidirectional"
draganddrop="hosttoguest"
vrde="off"
usb="on"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="home_Virtual_shared"
SharedFolderPathMachineMapping1="/Users/realyst/VirtualDevEnvironment/shared"
SharedFolderNameMachineMapping2="vagrant"
SharedFolderPathMachineMapping2="/Users/realyst/VirtualDevEnvironment"
vcpenabled="off"
vcpscreens=0
vcpfile="/Users/realyst/VirtualBox VMs/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473/VirtualDevEnvironment_Virtual_Dev_1493053977383_33473.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "storageattach", "592e0b5b-f2c6-4c3d-a0f1-f28f5929efe0", "--storagectl", "SATA", "--port", "4", "--device", "0", "--type", "hdd", "--medium", "/Users/realyst/ss_dev_projects.vdi", "--hotpluggable", "on"]
DEBUG subprocess: Command not in installer, not touching env vars.
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Boot:0x00000101a14aa8>
 INFO interface: info: Booting VM...
 INFO interface: info: ==> Virtual_Dev: Booting VM...
==> Virtual_Dev: Booting VM...
```

**Comment by realyst2k** [comment] 2017-04-24 18:13
Mounting it manually after boot appears to work:

sudo mount -t ext3 /dev/mapper/virtual--vg1-projects /mnt/projtest
[virtual@sitesell ~]$ ls -la /mnt/projdisk/
total 32
drwxr-xr-x 7 root     root     4096 Apr 24 13:31 .
drwxr-xr-x 5 root     root     4096 Apr 24 13:39 ..
drwxr-xr-x 3 virtual virtual 4096 Apr 14  2015 content
drwxr-xr-x 3 root     root     4096 Apr 24 13:31 cpan-sandbox
drwxr-xr-x 2 virtual virtual 4096 Apr 24 13:37 projects
drwx------ 2 virtual virtual 4096 Apr 24 13:31 ssh
drwxrwxrw- 2 virtual virtual 4096 Apr 24 13:31 subversion

But the plugin is failing to do this on boot for some reason.

**Comment by realyst2k** [comment] 2017-05-16 15:18
Anyone else running into this?

I've verified this is still an issue with the newest plugin version, Vagrant version and VirtualBox version.

**Comment by realyst2k** [comment] 2017-05-16 15:26
Seems like for whatever reason the fstab is not getting updated.

```
/dev/VolGroup00/LogVol00 /                       ext3    defaults        1 1
LABEL=/boot             /boot                   ext3    defaults        1 2
tmpfs                   /dev/shm                tmpfs   defaults        0 0
devpts                  /dev/pts                devpts  gid=5,mode=620  0 0
sysfs                   /sys                    sysfs   defaults        0 0
proc                    /proc                   proc    defaults        0 0
/dev/VolGroup00/LogVol01 swap                    swap    defaults        0 0
```

Though with no obvious errors. But what is '32' all about?

```
fdisk returned:  0
pvcreate returned:  0
vgcreate returned:  5
lvcreate returned:  5
vg activation returned:  5
ext3 creation return:  0
fstab update returned:  0
/mnt/projdisk mounting returned:  32
/home/sitesell/disk_operation_log.txt (END)
```

**Comment by nicolasbadia** [comment] 2017-10-11 19:04
Doesn't seem to works in vagrant 2.0.0 either.

**Comment by yaskoo** [comment] 2018-02-02 09:59
For me with vagrant 2.0.1, vbox 5.2.6 r120293 and vagrant-persistent-storage 0.0.41
The config is copy/paste from the docs - the disk gets created and mounted, after that I just created a text file with some data in it.
Destroyed the vm and uped it again ..everything seems to be normal, but the file I created - it's there, but it's empty.

**Comment by chucknelson** [comment] 2020-10-15 13:19
@kusnier - Since this plugin works fine with Vagrant `2.x` for the past 3-ish years, could this issue be closed?

**Comment by kusnier** [comment] 2020-10-16 12:33
> @kusnier - Since this plugin works fine with Vagrant `2.x` for the past 3-ish years, could this issue be closed?

Thanks. I will close it

**Closed by kusnier** 2020-10-16 12:33 UTC
