### ISSUE TITLE
How to add two disks?

### ISSUE THREAD

**Issue by acesuares** [kusnier/vagrant-persistent-storage#61] opened 2017-02-26 21:32 UTC
How to add two disks?

**Comment by macbeth76** [comment] 2017-06-02 15:45
I also would like to have two disks, is this possible?

**Comment by vmichnowicz** [comment] 2017-12-05 21:51
It does not look like adding multiple disks is currently supported. I think this would be a nice feature though.

**Comment by sporniket** [comment] 2018-05-29 13:05
This issues seems duplicate of #22 and should be closed

**Comment by kusnier** [comment] 2018-05-31 19:29
Duplicate Close #61
See #22

**Closed by kusnier** 2018-05-31 19:29 UTC
